import Link from 'next/link';
import Image from 'next/image';

export default function HomePage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-green-50 to-blue-50">
      <main className="container mx-auto px-4 py-16">
        {/* Temporary announcement banners */}
        <div className="space-y-3 mb-8">
          <div className="p-4 rounded-lg bg-green-50 border border-green-200 text-green-800">
            <p className="font-semibold">🚀 Site is Live!</p>
            <p className="text-sm">PetPlantr.com is successfully deployed. Upload and ordering features will be restored shortly.</p>
          </div>
          <div className="p-4 rounded-lg bg-yellow-50 border border-yellow-200 text-yellow-800">
            <p className="font-semibold">Upload functionality coming soon</p>
            <p className="text-sm">We're working on restoring the advanced features.</p>
          </div>
        </div>
        <section id="hero" className="text-center">
          <h1 className="text-6xl font-bold text-gray-900 mb-6">
            🐕 PetPlantr
          </h1>
          <p className="text-xl text-gray-600 mb-8 max-w-2xl mx-auto">
            Transform your pet photos into beautiful 3D planters using AI. 
            Upload a photo, get a custom planter design, and 3D print your creation!
          </p>
          {/* Hero Image */}
          <div className="mx-auto mb-8 rounded-lg shadow-lg max-w-full">
            <Image
              src="https://via.placeholder.com/800x400?text=Pet+Planter+Example"
              alt="Example of a 3D pet planter generated by AI"
              width={800}
              height={400}
              className="rounded-lg h-auto w-full"
              priority
            />
          </div>
        </section>

        <section id="steps" className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8 mt-12 max-w-4xl mx-auto">
          <div className="bg-white p-6 rounded-lg shadow-lg hover:shadow-xl hover:scale-105 transition-all duration-300">
            <div className="text-4xl mb-4" role="img" aria-label="Mobile upload icon">📱</div>
            <h3 className="text-lg font-semibold mb-3">Upload Photo</h3>
            <p className="text-gray-600">Snap or select a clear photo of your pet</p>
          </div>
          <div className="bg-white p-6 rounded-lg shadow-lg hover:shadow-xl hover:scale-105 transition-all duration-300">
            <div className="text-4xl mb-4" role="img" aria-label="AI processing icon">🤖</div>
            <h3 className="text-lg font-semibold mb-3">AI Magic</h3>
            <p className="text-gray-600">Our AI detects breed and creates a unique 3D model</p>
          </div>
          <div className="bg-white p-6 rounded-lg shadow-lg hover:shadow-xl hover:scale-105 transition-all duration-300">
            <div className="text-4xl mb-4" role="img" aria-label="Planter icon">🌱</div>
            <h3 className="text-lg font-semibold mb-3">Print & Plant</h3>
            <p className="text-gray-600">Download STL file and 3D print your pet planter</p>
          </div>
        </section>

        <section id="cta" className="mt-12 text-center">
          <Link href="/upload" passHref>
            <button 
              className="bg-green-600 hover:bg-green-700 text-white font-bold py-4 px-8 rounded-lg text-lg transition-all duration-300 shadow-lg hover:scale-105"
              aria-label="Get started by uploading your pet photo"
            >
              Get Started - Upload Your Pet Photo
            </button>
          </Link>
        </section>

        <section id="how-it-works" className="mt-16 text-center">
          <h2 className="text-2xl font-bold text-gray-800 mb-4">How It Works</h2>
          <div className="max-w-3xl mx-auto text-gray-600">
            <p className="mb-4">
              PetPlantr leverages advanced AI, including breed detection and 3D generation via Replicate models, 
              to analyze your pet's photo and craft a personalized planter that captures their essence.
            </p>
            <p className="mb-4">
              Simply upload, wait moments for processing, and receive a ready-to-print STL file. 
              It's fun, easy, and a perfect tribute to your furry friend!
            </p>
          </div>
        </section>

        <section id="examples" className="mt-16 text-center">
          <h2 className="text-2xl font-bold text-gray-800 mb-4">See Examples</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 max-w-4xl mx-auto">
            <Image
              src="https://via.placeholder.com/300?text=Before:+Pet+Photo"
              alt="Before: Original pet photo"
              width={300}
              height={300}
              className="rounded-lg shadow-md h-auto w-full"
            />
            <Image
              src="https://via.placeholder.com/300?text=AI+Processing"
              alt="During: AI generating 3D model"
              width={300}
              height={300}
              className="rounded-lg shadow-md h-auto w-full"
            />
            <Image
              src="https://via.placeholder.com/300?text=After:+3D+Planter"
              alt="After: Finished 3D pet planter"
              width={300}
              height={300}
              className="rounded-lg shadow-md h-auto w-full"
            />
          </div>
        </section>
      </main>
    </div>
  );
}