#!/usr/bin/env bash
# production-pipeline.sh - Complete production deployment pipeline for PetPlantr
# Orchestrates SSL setup, monitoring, and production deployment

set -euo pipefail

# Configuration
ENVIRONMENT="${ENVIRONMENT:-production}"
DOMAIN="${DOMAIN:-localhost}"
SSL_TYPE="${SSL_TYPE:-self-signed}"
MONITORING_ENABLED="${MONITORING_ENABLED:-true}"
CANARY_PERCENTAGE="${CANARY_PERCENTAGE:-10}"
FORCE="${FORCE:-false}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
NC='\033[0m'

# Logging
log_info() { echo -e "${BLUE}[INFO]${NC} $*" >&2; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*" >&2; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $*" >&2; }
log_stage() { echo -e "${PURPLE}[STAGE]${NC} $*" >&2; }

# Progress tracking
STAGE_FILE=".production_pipeline_stage"
CURRENT_STAGE=""

set_stage() {
    CURRENT_STAGE="$1"
    echo "$CURRENT_STAGE" > "$STAGE_FILE"
    log_stage "Starting: $CURRENT_STAGE"
}

complete_stage() {
    log_success "Completed: $CURRENT_STAGE"
    echo "COMPLETED_$(date +%s): $CURRENT_STAGE" >> "$STAGE_FILE"
}

# Check prerequisites
check_prerequisites() {
    set_stage "Checking Prerequisites"

    log_info "Checking system requirements..."

    # Check OS
    if [[ "$OSTYPE" != "darwin"* ]] && [[ "$OSTYPE" != "linux-gnu" ]]; then
        log_error "Unsupported OS: $OSTYPE"
        log_error "This pipeline supports macOS and Linux"
        exit 1
    fi

    # Check Docker
    if ! command -v docker >/dev/null 2>&1; then
        log_error "Docker is required but not installed"
        exit 1
    fi

    if ! docker info >/dev/null 2>&1; then
        log_error "Docker daemon is not running"
        exit 1
    fi

    # Check Docker Compose
    if ! command -v docker-compose >/dev/null 2>&1 && ! docker compose version >/dev/null 2>&1; then
        log_error "Docker Compose is required but not available"
        exit 1
    fi

    # Check required files
    local required_files=("api_server.py" "docker-compose.yml" "Dockerfile")
    for file in "${required_files[@]}"; do
        if [[ ! -f "$file" ]]; then
            log_error "Required file missing: $file"
            exit 1
        fi
    done

    # Check available disk space (minimum 5GB)
    local available_space
    available_space=$(df -BG . | tail -1 | awk '{print $4}' | sed 's/G//')
    if [[ $available_space -lt 5 ]]; then
        log_error "Insufficient disk space: ${available_space}GB available, minimum 5GB required"
        exit 1
    fi

    log_success "Prerequisites check passed"
    complete_stage
}

# Setup environment configuration
setup_environment() {
    set_stage "Environment Setup"

    log_info "Setting up production environment..."

    # Create environment file
    local env_file=".env.production"
    if [[ ! -f "$env_file" ]] || [[ "$FORCE" == "true" ]]; then
        cat > "$env_file" << EOF
# PetPlantr Production Environment Configuration
# Generated by production-pipeline.sh on $(date)

# Environment
ENVIRONMENT=$ENVIRONMENT
DOMAIN=$DOMAIN

# API Configuration
API_HOST=0.0.0.0
API_PORT=8000
API_WORKERS=4

# Security
SECRET_KEY=$(openssl rand -hex 32)
JWT_SECRET_KEY=$(openssl rand -hex 32)

# Database
REDIS_URL=redis://redis:6379/0

# External Services
REPLICATE_API_TOKEN=${REPLICATE_API_TOKEN:-}
OPENAI_API_KEY=${OPENAI_API_KEY:-}

# Monitoring
PROMETHEUS_METRICS_ENABLED=true
SENTRY_DSN=${SENTRY_DSN:-}

# Feature Flags
CANARY_DEPLOYMENT_ENABLED=true
CANARY_PERCENTAGE=$CANARY_PERCENTAGE
REQUEST_HEDGING_ENABLED=true
SYNTHETIC_MONITORING_ENABLED=true

# Logging
LOG_LEVEL=INFO
LOG_FORMAT=json

# Performance
MAX_REQUEST_SIZE=100MB
REQUEST_TIMEOUT=30
WORKER_TIMEOUT=300
EOF
        log_success "Environment file created: $env_file"
    else
        log_warn "Environment file already exists, skipping creation"
    fi

    # Create production directories
    mkdir -p logs
    mkdir -p backups
    mkdir -p security/ssl
    mkdir -p monitoring

    complete_stage
}

# Setup SSL certificates
setup_ssl() {
    set_stage "SSL Setup"

    log_info "Setting up SSL certificates..."

    if [[ "$SSL_TYPE" == "skip" ]]; then
        log_warn "SSL setup skipped"
        complete_stage
        return 0
    fi

    # Run SSL setup script
    if [[ -f "./setup-ssl.sh" ]]; then
        bash ./setup-ssl.sh \
            --domain "$DOMAIN" \
            --type "$SSL_TYPE" \
            --force
    else
        log_error "SSL setup script not found: setup-ssl.sh"
        exit 1
    fi

    complete_stage
}

# Setup monitoring stack
setup_monitoring() {
    set_stage "Monitoring Setup"

    if [[ "$MONITORING_ENABLED" != "true" ]]; then
        log_warn "Monitoring setup skipped"
        complete_stage
        return 0
    fi

    log_info "Setting up monitoring stack..."

    # Run monitoring setup script
    if [[ -f "./enable-monitoring.sh" ]]; then
        bash ./enable-monitoring.sh \
            --no-start \
            --force
    else
        log_error "Monitoring setup script not found: enable-monitoring.sh"
        exit 1
    fi

    complete_stage
}

# Pre-deployment validation
pre_deployment_validation() {
    set_stage "Pre-deployment Validation"

    log_info "Running pre-deployment validation..."

    # Validate Docker Compose configuration
    log_info "Validating Docker Compose configuration..."
    if docker compose config >/dev/null 2>&1; then
        log_success "Docker Compose configuration is valid"
    else
        log_error "Docker Compose configuration is invalid"
        exit 1
    fi

    # Check for port conflicts
    local ports=(8000 6379 5432)
    for port in "${ports[@]}"; do
        if lsof -Pi :$port -sTCP:LISTEN -t >/dev/null 2>&1; then
            log_error "Port $port is already in use"
            exit 1
        fi
    done
    log_success "No port conflicts detected"

    # Validate Python dependencies
    if [[ -f "requirements.txt" ]]; then
        log_info "Validating Python dependencies..."
        python3 -c "import pkg_resources; pkg_resources.require(open('requirements.txt').read())" 2>/dev/null && \
            log_success "Python dependencies are valid" || \
            log_error "Python dependencies validation failed"
    fi

    # Test API server startup (dry run)
    log_info "Testing API server startup..."
    timeout 10s python3 -c "
import sys
sys.path.append('.')
try:
    from api_server import app
    print('API server imports successfully')
except Exception as e:
    print(f'API server import failed: {e}')
    sys.exit(1)
" || {
        log_error "API server validation failed"
        exit 1
    }

    complete_stage
}

# Deploy application
deploy_application() {
    set_stage "Application Deployment"

    log_info "Deploying PetPlantr application..."

    # Stop existing containers
    log_info "Stopping existing containers..."
    docker compose down --remove-orphans 2>/dev/null || true

    # Build and start services
    log_info "Building and starting services..."
    docker compose up -d --build

    # Wait for services to start
    log_info "Waiting for services to start..."
    local max_attempts=30
    local attempt=1

    while [[ $attempt -le $max_attempts ]]; do
        if docker compose ps | grep -q "Up"; then
            log_success "Services are starting up..."
            break
        fi
        sleep 2
        ((attempt++))
    done

    if [[ $attempt -gt $max_attempts ]]; then
        log_error "Services failed to start within timeout"
        docker compose logs
        exit 1
    fi

    complete_stage
}

# Post-deployment validation
post_deployment_validation() {
    set_stage "Post-deployment Validation"

    log_info "Running post-deployment validation..."

    # Wait for API to be ready
    log_info "Waiting for API to be ready..."
    local max_attempts=30
    local attempt=1

    while [[ $attempt -le $max_attempts ]]; do
        if curl -f -s "http://localhost:8000/api/v1/health" >/dev/null 2>&1; then
            log_success "API is responding"
            break
        fi
        sleep 2
        ((attempt++))
    done

    if [[ $attempt -gt $max_attempts ]]; then
        log_error "API failed to respond within timeout"
        docker compose logs api
        exit 1
    fi

    # Validate health endpoint
    local health_response
    health_response=$(curl -s "http://localhost:8000/api/v1/health")
    if echo "$health_response" | grep -q '"status":"healthy"'; then
        log_success "Health check passed"
    else
        log_error "Health check failed: $health_response"
        exit 1
    fi

    # Test synthetic monitor
    if curl -f -s "http://localhost:8000/api/v1/synthetic-monitor" >/dev/null 2>&1; then
        log_success "Synthetic monitor is responding"
    else
        log_error "Synthetic monitor check failed"
        exit 1
    fi

    # Validate canary configuration
    if [[ -f "nginx/local-canary.conf" ]]; then
        if grep -q "$CANARY_PERCENTAGE%" nginx/local-canary.conf; then
            log_success "Canary configuration validated ($CANARY_PERCENTAGE% traffic)"
        else
            log_warn "Canary percentage not found in configuration"
        fi
    fi

    complete_stage
}

# Start monitoring stack
start_monitoring_services() {
    set_stage "Monitoring Services"

    if [[ "$MONITORING_ENABLED" != "true" ]]; then
        log_warn "Monitoring services skipped"
        complete_stage
        return 0
    fi

    log_info "Starting monitoring services..."

    cd monitoring
    if docker compose -f docker-compose.monitoring.yml up -d; then
        log_success "Monitoring services started"
    else
        log_error "Failed to start monitoring services"
        cd -
        exit 1
    fi
    cd -

    # Wait for monitoring services
    sleep 10

    # Validate monitoring services
    if curl -f -s "http://localhost:9090/-/healthy" >/dev/null 2>&1; then
        log_success "Prometheus is healthy"
    else
        log_warn "Prometheus health check failed"
    fi

    if curl -f -s "http://localhost:3000/api/health" >/dev/null 2>&1; then
        log_success "Grafana is healthy"
    else
        log_warn "Grafana health check failed"
    fi

    complete_stage
}

# Generate deployment report
generate_deployment_report() {
    set_stage "Deployment Report"

    log_info "Generating deployment report..."

    local report_file="reports/production-deployment-$(date +%Y%m%d-%H%M%S).md"

    mkdir -p reports

    cat > "$report_file" << EOF
# PetPlantr Production Deployment Report
Generated: $(date)
Environment: $ENVIRONMENT
Domain: $DOMAIN

## Deployment Summary
- SSL Type: $SSL_TYPE
- Monitoring: $MONITORING_ENABLED
- Canary Percentage: $CANARY_PERCENTAGE%

## Services Status
$(docker compose ps --format "table {{.Name}}\t{{.Status}}\t{{.Ports}}")

## Health Checks
- API Health: $(curl -s "http://localhost:8000/api/v1/health" | jq -r '.status' 2>/dev/null || echo "Failed")
- Synthetic Monitor: $(curl -s "http://localhost:8000/api/v1/synthetic-monitor" | jq -r '.status' 2>/dev/null || echo "Failed")

## Access URLs
- API: http://localhost:8000
- Health: http://localhost:8000/api/v1/health
- Synthetic Monitor: http://localhost:8000/api/v1/synthetic-monitor
EOF

    if [[ "$MONITORING_ENABLED" == "true" ]]; then
        cat >> "$report_file" << EOF

## Monitoring URLs
- Prometheus: http://localhost:9090
- Grafana: http://localhost:3000 (admin/admin)
- Alertmanager: http://localhost:9093
EOF
    fi

    if [[ "$SSL_TYPE" != "skip" ]]; then
        cat >> "$report_file" << EOF

## SSL Configuration
- Certificate Type: $SSL_TYPE
- Certificate Path: ./security/ssl/certs/
- Private Key Path: ./security/ssl/private/
EOF
    fi

    cat >> "$report_file" << EOF

## Next Steps
1. Update DNS to point $DOMAIN to this server
2. Configure production domain SSL certificates
3. Set up automated backups
4. Configure alerting notifications
5. Monitor canary deployment metrics
6. Gradually increase canary traffic percentage

## Rollback Plan
To rollback this deployment:
\`\`\`bash
docker compose down
git checkout <previous-commit>
docker compose up -d --build
\`\`\`

## Logs
Application logs: docker compose logs -f
Monitoring logs: cd monitoring && docker compose -f docker-compose.monitoring.yml logs -f
EOF

    log_success "Deployment report generated: $report_file"
    complete_stage
}

# Cleanup and finalization
cleanup_and_finalize() {
    set_stage "Cleanup and Finalization"

    log_info "Performing final cleanup..."

    # Remove temporary files
    rm -f "$STAGE_FILE"

    # Set proper permissions
    chmod 600 .env.production 2>/dev/null || true

    # Create backup of current deployment
    local backup_dir="backups/deployment-$(date +%Y%m%d-%H%M%S)"
    mkdir -p "$backup_dir"
    cp docker-compose.yml "$backup_dir/" 2>/dev/null || true
    cp .env.production "$backup_dir/" 2>/dev/null || true

    log_success "Cleanup completed"
    complete_stage
}

# Recovery function
recovery() {
    if [[ -f "$STAGE_FILE" ]]; then
        local last_stage
        last_stage=$(tail -1 "$STAGE_FILE")
        if [[ "$last_stage" == COMPLETED_* ]]; then
            log_info "Previous deployment completed successfully"
            return 0
        fi

        log_warn "Previous deployment was interrupted at stage: $last_stage"
        log_info "Resuming from interrupted deployment..."

        # Resume from the last incomplete stage
        case "$last_stage" in
            "Checking Prerequisites")
                setup_environment
                setup_ssl
                setup_monitoring
                pre_deployment_validation
                deploy_application
                post_deployment_validation
                start_monitoring_services
                generate_deployment_report
                cleanup_and_finalize
                ;;
            "Environment Setup")
                setup_ssl
                setup_monitoring
                pre_deployment_validation
                deploy_application
                post_deployment_validation
                start_monitoring_services
                generate_deployment_report
                cleanup_and_finalize
                ;;
            "SSL Setup")
                setup_monitoring
                pre_deployment_validation
                deploy_application
                post_deployment_validation
                start_monitoring_services
                generate_deployment_report
                cleanup_and_finalize
                ;;
            "Monitoring Setup")
                pre_deployment_validation
                deploy_application
                post_deployment_validation
                start_monitoring_services
                generate_deployment_report
                cleanup_and_finalize
                ;;
            "Pre-deployment Validation")
                deploy_application
                post_deployment_validation
                start_monitoring_services
                generate_deployment_report
                cleanup_and_finalize
                ;;
            "Application Deployment")
                post_deployment_validation
                start_monitoring_services
                generate_deployment_report
                cleanup_and_finalize
                ;;
            "Post-deployment Validation")
                start_monitoring_services
                generate_deployment_report
                cleanup_and_finalize
                ;;
            "Monitoring Services")
                generate_deployment_report
                cleanup_and_finalize
                ;;
            "Deployment Report")
                cleanup_and_finalize
                ;;
            *)
                log_info "Starting fresh deployment..."
                ;;
        esac
    fi
}

# Main pipeline function
main() {
    log_info "🚀 Starting PetPlantr Production Deployment Pipeline"
    log_info "Environment: $ENVIRONMENT"
    log_info "Domain: $DOMAIN"
    log_info "SSL Type: $SSL_TYPE"
    log_info "Monitoring: $MONITORING_ENABLED"
    log_info "Canary: $CANARY_PERCENTAGE%"
    echo

    # Recovery check
    recovery

    # Execute pipeline stages
    check_prerequisites
    setup_environment
    setup_ssl
    setup_monitoring
    pre_deployment_validation
    deploy_application
    post_deployment_validation
    start_monitoring_services
    generate_deployment_report
    cleanup_and_finalize

    log_success "🎉 Production deployment completed successfully!"
    echo
    log_info "📊 Deployment Summary:"
    log_info "  ✅ Application deployed and healthy"
    log_info "  ✅ Canary deployment configured ($CANARY_PERCENTAGE% traffic)"
    [[ "$SSL_TYPE" != "skip" ]] && log_info "  ✅ SSL certificates configured"
    [[ "$MONITORING_ENABLED" == "true" ]] && log_info "  ✅ Monitoring stack operational"
    echo
    log_info "🔗 Access URLs:"
    log_info "  API: http://localhost:8000"
    log_info "  Health: http://localhost:8000/api/v1/health"
    [[ "$MONITORING_ENABLED" == "true" ]] && log_info "  Monitoring: http://localhost:3000"
    echo
    log_info "📋 Check the deployment report in reports/ for detailed information"
}

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --environment)
            ENVIRONMENT="$2"
            shift 2
            ;;
        --domain)
            DOMAIN="$2"
            shift 2
            ;;
        --ssl-type)
            SSL_TYPE="$2"
            shift 2
            ;;
        --canary-percentage)
            CANARY_PERCENTAGE="$2"
            shift 2
            ;;
        --no-monitoring)
            MONITORING_ENABLED=false
            shift
            ;;
        --force)
            FORCE=true
            shift
            ;;
        --help)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Complete production deployment pipeline for PetPlantr"
            echo ""
            echo "Options:"
            echo "  --environment ENV       Environment name (default: production)"
            echo "  --domain DOMAIN         Domain name (default: localhost)"
            echo "  --ssl-type TYPE         SSL type: self-signed, letsencrypt, custom, skip (default: self-signed)"
            echo "  --canary-percentage PCT Canary traffic percentage (default: 10)"
            echo "  --no-monitoring         Skip monitoring stack setup"
            echo "  --force                 Force regeneration of configurations"
            echo "  --help                  Show this help"
            echo ""
            echo "Examples:"
            echo "  $0 --domain petplantr.com --ssl-type letsencrypt"
            echo "  $0 --canary-percentage 25 --no-monitoring"
            exit 0
            ;;
        *)
            log_error "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Validate canary percentage
if [[ $CANARY_PERCENTAGE -lt 0 ]] || [[ $CANARY_PERCENTAGE -gt 100 ]]; then
    log_error "Canary percentage must be between 0 and 100"
    exit 1
fi

# Run main pipeline
main