services:
  grafana:
    image: grafana/grafana:10.4.5
    environment:
      - PROMETHEUS_URL=${PROMETHEUS_URL:-http://prometheus:9090}
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3001:3000"
