name: CI
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  sprint-c:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install test requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test-sprint-c.txt
          # Ensure optional deps present for marked tests
          pip install fakeredis respx pytest-asyncio pytest-cov
      - name: Run sprint-c tests (isolated plugins)
        env:
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
        run: pytest -q -m sprint_c -c pytest.ini
