name: Release Drafter
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, reopened, closed, labeled, unlabeled, synchronize]
permissions:
  contents: write
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release-drafter.yml
